--- 
 - name: Insert an entry in /etc/hosts {{ ansible_hostname }}
   lineinfile:
    destfile: /etc/hosts
    line: '{{ IP }}  monitor.lybrate.com'

 - name: Download Zabbix Ubuntu 16 (Xenial) release deb file
    get_url:
       url=http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
       dest=/opt/zabbix-release_3.2-1+xenial_all.deb

 - name: Apt install Zabbix release in Ubuntu/Debian
    apt: deb=/opt/zabbix-release_3.2-1+xenial_all.deb
 
 - name: Update the cache...
    apt:
     update_cache: yes

 - name: Installing Zabbix Agent ...
    apt: name=zabbix-agent state=installed
 
 - name: Configuring Zabbix Agent ...
    template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644
    notify: zabbix-agent restart
